export const corporateBuyerScreens = [
  {
    "id": "961:256",
    "name": "Corporate Buyer / Dashboard — Desktop",
    "w": 1440,
    "h": 1024,
    "section": "01 — Foundation & Dashboard",
    "slug": "dashboard",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  },
  {
    "id": "961:415",
    "name": "Corporate Buyer / Corporate Products — Desktop",
    "w": 1440,
    "h": 1038,
    "section": "02 — Corporate Products",
    "slug": "corporate-products",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  },
  {
    "id": "961:590",
    "name": "Corporate Buyer / Product Detail — Desktop",
    "w": 1440,
    "h": 1024,
    "section": "02 — Corporate Products",
    "slug": "product-detail",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  },
  {
    "id": "961:705",
    "name": "Corporate Buyer / Artist Profile — Desktop",
    "w": 1440,
    "h": 1024,
    "section": "02 — Corporate Products",
    "slug": "artist-profile",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  },
  {
    "id": "961:949",
    "name": "Corporate Buyer / Purchase Requests — Desktop",
    "w": 1440,
    "h": 1024,
    "section": "03 — Purchase Requests",
    "slug": "purchase-requests",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  },
  {
    "id": "961:1109",
    "name": "Corporate Buyer / New Purchase Request — Desktop",
    "w": 1440,
    "h": 1038,
    "section": "03 — Purchase Requests",
    "slug": "new-purchase-request",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  },
  {
    "id": "961:1224",
    "name": "Corporate Buyer / Purchase Request Detail — Desktop",
    "w": 1440,
    "h": 1024,
    "section": "03 — Purchase Requests",
    "slug": "purchase-request-detail",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  },
  {
    "id": "961:1348",
    "name": "Corporate Buyer / Request Needs Info — Desktop",
    "w": 1440,
    "h": 1046,
    "section": "03 — Purchase Requests",
    "slug": "request-needs-info",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  },
  {
    "id": "961:1496",
    "name": "Corporate Buyer / Proposals — Desktop",
    "w": 1440,
    "h": 1024,
    "section": "04 — Proposals",
    "slug": "proposals",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  },
  {
    "id": "961:1625",
    "name": "Corporate Buyer / Proposal Detail — Desktop",
    "w": 1440,
    "h": 1215,
    "section": "04 — Proposals",
    "slug": "proposal-detail",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  },
  {
    "id": "961:1811",
    "name": "Corporate Buyer / Proposal Revision — Desktop",
    "w": 1440,
    "h": 1024,
    "section": "04 — Proposals",
    "slug": "proposal-revision",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  },
  {
    "id": "961:1919",
    "name": "Corporate Buyer / Order Submitted — Desktop",
    "w": 1440,
    "h": 1024,
    "section": "05 — Corporate Orders",
    "slug": "order-submitted",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  },
  {
    "id": "961:2044",
    "name": "Corporate Buyer / Orders — Desktop",
    "w": 1440,
    "h": 1067,
    "section": "05 — Corporate Orders",
    "slug": "orders",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  },
  {
    "id": "961:2234",
    "name": "Corporate Buyer / Order Detail — Desktop",
    "w": 1440,
    "h": 1133,
    "section": "05 — Corporate Orders",
    "slug": "order-detail",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  },
  {
    "id": "961:2426",
    "name": "Corporate Buyer / Deliveries — Desktop",
    "w": 1440,
    "h": 1067,
    "section": "06 — Fulfillment & Delivery",
    "slug": "deliveries",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  },
  {
    "id": "961:2578",
    "name": "Corporate Buyer / Delivery Detail — Desktop",
    "w": 1440,
    "h": 1067,
    "section": "06 — Fulfillment & Delivery",
    "slug": "delivery-detail",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  },
  {
    "id": "962:246",
    "name": "Corporate Buyer / Report Issue — Desktop",
    "w": 1440,
    "h": 1059,
    "section": "06 — Fulfillment & Delivery",
    "slug": "report-issue",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  },
  {
    "id": "962:363",
    "name": "Corporate Buyer / Issue Detail — Desktop",
    "w": 1440,
    "h": 1024,
    "section": "06 — Fulfillment & Delivery",
    "slug": "issue-detail",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  },
  {
    "id": "962:496",
    "name": "Corporate Buyer / Reports — Desktop",
    "w": 1440,
    "h": 1024,
    "section": "07 — Reports",
    "slug": "reports",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  },
  {
    "id": "962:620",
    "name": "Corporate Buyer / Notifications — Desktop",
    "w": 1440,
    "h": 1024,
    "section": "07 — Reports",
    "slug": "notifications",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  },
  {
    "id": "962:832",
    "name": "Corporate Buyer / Account — Desktop",
    "w": 1440,
    "h": 1407,
    "section": "08 — Organization Account & Access",
    "slug": "account",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  },
  {
    "id": "962:980",
    "name": "Corporate Buyer / Users & Access — Desktop",
    "w": 1440,
    "h": 1024,
    "section": "08 — Organization Account & Access",
    "slug": "users-and-access",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  },
  {
    "id": "962:1101",
    "name": "Corporate Buyer / Delivery Addresses — Desktop",
    "w": 1440,
    "h": 1024,
    "section": "08 — Organization Account & Access",
    "slug": "delivery-addresses",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  },
  {
    "id": "962:1227",
    "name": "Corporate Buyer / Empty States — Desktop",
    "w": 1440,
    "h": 1024,
    "section": "09 — States & QA",
    "slug": "empty-states",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  },
  {
    "id": "962:1321",
    "name": "Corporate Buyer / Loading States — Desktop",
    "w": 1440,
    "h": 1024,
    "section": "09 — States & QA",
    "slug": "loading-states",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  },
  {
    "id": "962:1472",
    "name": "Corporate Buyer / Error States — Desktop",
    "w": 1440,
    "h": 1024,
    "section": "09 — States & QA",
    "slug": "error-states",
    "implemented": true,
    "missingImageSlots": 0,
    "pendingReason": null
  }
] as const;
export const corporateBuyerLoaders = {
 "dashboard": () => import("./screens/dashboard"),
 "corporate-products": () => import("./screens/corporate-products"),
 "product-detail": () => import("./screens/product-detail"),
 "artist-profile": () => import("./screens/artist-profile"),
 "purchase-requests": () => import("./screens/purchase-requests"),
 "new-purchase-request": () => import("./screens/new-purchase-request"),
 "purchase-request-detail": () => import("./screens/purchase-request-detail"),
 "request-needs-info": () => import("./screens/request-needs-info"),
 "proposals": () => import("./screens/proposals"),
 "proposal-detail": () => import("./screens/proposal-detail"),
 "proposal-revision": () => import("./screens/proposal-revision"),
 "order-submitted": () => import("./screens/order-submitted"),
 "orders": () => import("./screens/orders"),
 "order-detail": () => import("./screens/order-detail"),
 "deliveries": () => import("./screens/deliveries"),
 "delivery-detail": () => import("./screens/delivery-detail"),
 "report-issue": () => import("./screens/report-issue"),
 "issue-detail": () => import("./screens/issue-detail"),
 "reports": () => import("./screens/reports"),
 "notifications": () => import("./screens/notifications"),
 "account": () => import("./screens/account"),
 "users-and-access": () => import("./screens/users-and-access"),
 "delivery-addresses": () => import("./screens/delivery-addresses"),
 "empty-states": () => import("./screens/empty-states"),
 "loading-states": () => import("./screens/loading-states"),
 "error-states": () => import("./screens/error-states")
};
export type CorporateBuyerScreenSlug = keyof typeof corporateBuyerLoaders;
