export const adminScreens = [
  {
    "id": "870:200",
    "name": "Admin / Dashboard — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "01 — Admin Foundation",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "dashboard",
    "pendingReason": null
  },
  {
    "id": "870:394",
    "name": "Admin / Dashboard — No Pending Actions",
    "w": 1440,
    "h": 1100,
    "section": "01 — Admin Foundation",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "dashboard-no-pending-actions",
    "pendingReason": null
  },
  {
    "id": "870:500",
    "name": "Admin / Dashboard — Loading",
    "w": 1440,
    "h": 1100,
    "section": "01 — Admin Foundation",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "dashboard-loading",
    "pendingReason": null
  },
  {
    "id": "870:618",
    "name": "Admin / Dashboard — Error",
    "w": 1440,
    "h": 1100,
    "section": "01 — Admin Foundation",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "dashboard-error",
    "pendingReason": null
  },
  {
    "id": "884:196",
    "name": "Admin / Artists — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "02 — Artists & Credentials",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "artists",
    "pendingReason": null
  },
  {
    "id": "884:457",
    "name": "Admin / Artists — Loading",
    "w": 1440,
    "h": 1100,
    "section": "02 — Artists & Credentials",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "artists-loading",
    "pendingReason": null
  },
  {
    "id": "884:586",
    "name": "Admin / Artists — Empty",
    "w": 1440,
    "h": 1100,
    "section": "02 — Artists & Credentials",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "artists-empty",
    "pendingReason": null
  },
  {
    "id": "884:668",
    "name": "Admin / Artists — Error",
    "w": 1440,
    "h": 1100,
    "section": "02 — Artists & Credentials",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "artists-error",
    "pendingReason": null
  },
  {
    "id": "884:753",
    "name": "Admin / Artist Detail — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "02 — Artists & Credentials",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "artist-detail",
    "pendingReason": null
  },
  {
    "id": "884:960",
    "name": "Admin / Professional Credentials — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "02 — Artists & Credentials",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "professional-credentials",
    "pendingReason": null
  },
  {
    "id": "884:1162",
    "name": "Admin / Credential Review — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "02 — Artists & Credentials",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "credential-review",
    "pendingReason": null
  },
  {
    "id": "884:1309",
    "name": "Admin / Credential Request Replacement",
    "w": 1440,
    "h": 1100,
    "section": "02 — Artists & Credentials",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "credential-request-replacement",
    "pendingReason": null
  },
  {
    "id": "884:1484",
    "name": "Admin / Credential Approve — Confirmation",
    "w": 1440,
    "h": 1100,
    "section": "02 — Artists & Credentials",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "credential-approve-confirmation",
    "pendingReason": null
  },
  {
    "id": "887:206",
    "name": "Admin / Products — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "03 — Products & Product Review",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "products",
    "pendingReason": null
  },
  {
    "id": "887:508",
    "name": "Admin / Products — Loading",
    "w": 1440,
    "h": 1100,
    "section": "03 — Products & Product Review",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "products-loading",
    "pendingReason": null
  },
  {
    "id": "887:629",
    "name": "Admin / Products — Empty",
    "w": 1440,
    "h": 1100,
    "section": "03 — Products & Product Review",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "products-empty",
    "pendingReason": null
  },
  {
    "id": "887:728",
    "name": "Admin / Products — Error",
    "w": 1440,
    "h": 1100,
    "section": "03 — Products & Product Review",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "products-error",
    "pendingReason": null
  },
  {
    "id": "887:815",
    "name": "Admin / Product Detail — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "03 — Products & Product Review",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "product-detail",
    "pendingReason": null
  },
  {
    "id": "887:1216",
    "name": "Admin / Product Review Queue — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "03 — Products & Product Review",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "product-review-queue",
    "pendingReason": null
  },
  {
    "id": "887:1461",
    "name": "Admin / Product Review — New Product — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "03 — Products & Product Review",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "product-review-new-product",
    "pendingReason": null
  },
  {
    "id": "887:1628",
    "name": "Admin / Product Review — Request Revision",
    "w": 1440,
    "h": 1100,
    "section": "03 — Products & Product Review",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "product-review-request-revision",
    "pendingReason": null
  },
  {
    "id": "887:1816",
    "name": "Admin / Product Review — Approve Confirmation",
    "w": 1440,
    "h": 1100,
    "section": "03 — Products & Product Review",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "product-review-approve-confirmation",
    "pendingReason": null
  },
  {
    "id": "887:2066",
    "name": "Admin / Product Review — Published Changes — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "03 — Products & Product Review",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "product-review-published-changes",
    "pendingReason": null
  },
  {
    "id": "887:2254",
    "name": "Admin / Product Review — Changes Request Revision",
    "w": 1440,
    "h": 1100,
    "section": "03 — Products & Product Review",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "product-review-changes-request-revision",
    "pendingReason": null
  },
  {
    "id": "887:2468",
    "name": "Admin / Product Review — Changes Approve Confirmation",
    "w": 1440,
    "h": 1100,
    "section": "03 — Products & Product Review",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "product-review-changes-approve-confirmation",
    "pendingReason": null
  },
  {
    "id": "888:206",
    "name": "Admin / Orders — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "04 — Orders, Issues & Shipping",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "orders",
    "pendingReason": null
  },
  {
    "id": "888:465",
    "name": "Admin / Orders — Loading",
    "w": 1440,
    "h": 1100,
    "section": "04 — Orders, Issues & Shipping",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "orders-loading",
    "pendingReason": null
  },
  {
    "id": "888:556",
    "name": "Admin / Orders — Empty",
    "w": 1440,
    "h": 1100,
    "section": "04 — Orders, Issues & Shipping",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "orders-empty",
    "pendingReason": null
  },
  {
    "id": "888:646",
    "name": "Admin / Orders — Error",
    "w": 1440,
    "h": 1100,
    "section": "04 — Orders, Issues & Shipping",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "orders-error",
    "pendingReason": null
  },
  {
    "id": "888:730",
    "name": "Admin / Order Detail — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "04 — Orders, Issues & Shipping",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "order-detail",
    "pendingReason": null
  },
  {
    "id": "888:915",
    "name": "Admin / Orders — Needs Action — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "04 — Orders, Issues & Shipping",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "orders-needs-action",
    "pendingReason": null
  },
  {
    "id": "888:1092",
    "name": "Admin / Order Issues — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "04 — Orders, Issues & Shipping",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "order-issues",
    "pendingReason": null
  },
  {
    "id": "888:1299",
    "name": "Admin / Order Issue Detail — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "04 — Orders, Issues & Shipping",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "order-issue-detail",
    "pendingReason": null
  },
  {
    "id": "888:1490",
    "name": "Admin / Shipping Operations — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "04 — Orders, Issues & Shipping",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "shipping-operations",
    "pendingReason": null
  },
  {
    "id": "888:1708",
    "name": "Admin / Shipment Detail — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "04 — Orders, Issues & Shipping",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "shipment-detail",
    "pendingReason": null
  },
  {
    "id": "892:233",
    "name": "Admin / Growth Overview — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "05 — Growth, Services & Service Partners",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "growth-overview",
    "pendingReason": null
  },
  {
    "id": "892:411",
    "name": "Admin / Growth Reviews — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "05 — Growth, Services & Service Partners",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "growth-reviews",
    "pendingReason": null
  },
  {
    "id": "892:619",
    "name": "Admin / Growth Artist Detail — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "05 — Growth, Services & Service Partners",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "growth-artist-detail",
    "pendingReason": null
  },
  {
    "id": "892:785",
    "name": "Admin / Services — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "05 — Growth, Services & Service Partners",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "services",
    "pendingReason": null
  },
  {
    "id": "892:958",
    "name": "Admin / Service Requests — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "05 — Growth, Services & Service Partners",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "service-requests",
    "pendingReason": null
  },
  {
    "id": "892:1350",
    "name": "Admin / Services — Needs Assignment — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "05 — Growth, Services & Service Partners",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "services-needs-assignment",
    "pendingReason": null
  },
  {
    "id": "892:1497",
    "name": "Admin / Service Request Detail — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "05 — Growth, Services & Service Partners",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "service-request-detail",
    "pendingReason": null
  },
  {
    "id": "892:1683",
    "name": "Admin / Service Assignment — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "05 — Growth, Services & Service Partners",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "service-assignment",
    "pendingReason": null
  },
  {
    "id": "892:1829",
    "name": "Admin / Service Partners — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "05 — Growth, Services & Service Partners",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "service-partners",
    "pendingReason": null
  },
  {
    "id": "892:2031",
    "name": "Admin / Service Partner Detail — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "05 — Growth, Services & Service Partners",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "service-partner-detail",
    "pendingReason": null
  },
  {
    "id": "894:229",
    "name": "Admin / Opportunities — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "06 — Opportunities, Corporate & Organizations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "opportunities",
    "pendingReason": null
  },
  {
    "id": "894:478",
    "name": "Admin / Opportunities — Loading",
    "w": 1440,
    "h": 1100,
    "section": "06 — Opportunities, Corporate & Organizations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "opportunities-loading",
    "pendingReason": null
  },
  {
    "id": "894:602",
    "name": "Admin / Opportunities — Empty",
    "w": 1440,
    "h": 1100,
    "section": "06 — Opportunities, Corporate & Organizations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "opportunities-empty",
    "pendingReason": null
  },
  {
    "id": "894:695",
    "name": "Admin / Opportunities — Error",
    "w": 1440,
    "h": 1100,
    "section": "06 — Opportunities, Corporate & Organizations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "opportunities-error",
    "pendingReason": null
  },
  {
    "id": "894:781",
    "name": "Admin / Opportunity Detail — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "06 — Opportunities, Corporate & Organizations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "opportunity-detail",
    "pendingReason": null
  },
  {
    "id": "894:1169",
    "name": "Admin / Opportunity Applications — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "06 — Opportunities, Corporate & Organizations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "opportunity-applications",
    "pendingReason": null
  },
  {
    "id": "894:1410",
    "name": "Admin / Opportunity Application Detail — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "06 — Opportunities, Corporate & Organizations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "opportunity-application-detail",
    "pendingReason": null
  },
  {
    "id": "894:1573",
    "name": "Admin / Capacity Matching — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "06 — Opportunities, Corporate & Organizations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "capacity-matching",
    "pendingReason": null
  },
  {
    "id": "894:1733",
    "name": "Admin / Order Allocation — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "06 — Opportunities, Corporate & Organizations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "order-allocation",
    "pendingReason": null
  },
  {
    "id": "894:2067",
    "name": "Admin / Corporate Request Detail — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "06 — Opportunities, Corporate & Organizations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "corporate-request-detail",
    "pendingReason": null
  },
  {
    "id": "894:2249",
    "name": "Admin / Corporate Requests — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "06 — Opportunities, Corporate & Organizations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "corporate-requests",
    "pendingReason": null
  },
  {
    "id": "894:2456",
    "name": "Admin / Corporate Buyer Detail — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "06 — Opportunities, Corporate & Organizations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "corporate-buyer-detail",
    "pendingReason": null
  },
  {
    "id": "894:2628",
    "name": "Admin / Corporate Buyers — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "06 — Opportunities, Corporate & Organizations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "corporate-buyers",
    "pendingReason": null
  },
  {
    "id": "894:2983",
    "name": "Admin / Supporting Organizations — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "06 — Opportunities, Corporate & Organizations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "supporting-organizations",
    "pendingReason": null
  },
  {
    "id": "894:3161",
    "name": "Admin / Supporting Organization Detail — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "06 — Opportunities, Corporate & Organizations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "supporting-organization-detail",
    "pendingReason": null
  },
  {
    "id": "894:3355",
    "name": "Admin / Organization Artist Referrals — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "06 — Opportunities, Corporate & Organizations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "organization-artist-referrals",
    "pendingReason": null
  },
  {
    "id": "894:3553",
    "name": "Admin / Finance Overview — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "07 — Finance, Settlements & Memberships",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "finance-overview",
    "pendingReason": null
  },
  {
    "id": "894:3749",
    "name": "Admin / Settlement Requests — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "07 — Finance, Settlements & Memberships",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "settlement-requests",
    "pendingReason": null
  },
  {
    "id": "894:3948",
    "name": "Admin / Settlement Detail — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "07 — Finance, Settlements & Memberships",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "settlement-detail",
    "pendingReason": null
  },
  {
    "id": "894:4122",
    "name": "Admin / Settlement Review — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "07 — Finance, Settlements & Memberships",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "settlement-review",
    "pendingReason": null
  },
  {
    "id": "894:4279",
    "name": "Admin / Settlement Confirmation — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "07 — Finance, Settlements & Memberships",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "settlement-confirmation",
    "pendingReason": null
  },
  {
    "id": "894:4387",
    "name": "Admin / Transactions — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "07 — Finance, Settlements & Memberships",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "transactions",
    "pendingReason": null
  },
  {
    "id": "894:4587",
    "name": "Admin / Transaction Detail — Sale",
    "w": 1440,
    "h": 1100,
    "section": "07 — Finance, Settlements & Memberships",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "transaction-detail-sale",
    "pendingReason": null
  },
  {
    "id": "894:4715",
    "name": "Admin / Transaction Detail — Settlement",
    "w": 1440,
    "h": 1100,
    "section": "07 — Finance, Settlements & Memberships",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "transaction-detail-settlement",
    "pendingReason": null
  },
  {
    "id": "894:4840",
    "name": "Admin / Transaction Detail — Refund",
    "w": 1440,
    "h": 1100,
    "section": "07 — Finance, Settlements & Memberships",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "transaction-detail-refund",
    "pendingReason": null
  },
  {
    "id": "894:5150",
    "name": "Admin / Memberships — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "07 — Finance, Settlements & Memberships",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "memberships",
    "pendingReason": null
  },
  {
    "id": "894:5341",
    "name": "Admin / Membership Detail — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "07 — Finance, Settlements & Memberships",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "membership-detail",
    "pendingReason": null
  },
  {
    "id": "894:5496",
    "name": "Admin / Membership Upgrade Detail — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "07 — Finance, Settlements & Memberships",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "membership-upgrade-detail",
    "pendingReason": null
  },
  {
    "id": "894:5635",
    "name": "Admin / Stories — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "08 — Stories, Content & Moderation",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "stories",
    "pendingReason": null
  },
  {
    "id": "894:5868",
    "name": "Admin / Stories — Loading",
    "w": 1440,
    "h": 1100,
    "section": "08 — Stories, Content & Moderation",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "stories-loading",
    "pendingReason": null
  },
  {
    "id": "894:5982",
    "name": "Admin / Stories — Empty",
    "w": 1440,
    "h": 1100,
    "section": "08 — Stories, Content & Moderation",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "stories-empty",
    "pendingReason": null
  },
  {
    "id": "894:6071",
    "name": "Admin / Stories — Error",
    "w": 1440,
    "h": 1100,
    "section": "08 — Stories, Content & Moderation",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "stories-error",
    "pendingReason": null
  },
  {
    "id": "894:6148",
    "name": "Admin / Story Detail — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "08 — Stories, Content & Moderation",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "story-detail",
    "pendingReason": null
  },
  {
    "id": "894:6541",
    "name": "Admin / Story Review Queue — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "08 — Stories, Content & Moderation",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "story-review-queue",
    "pendingReason": null
  },
  {
    "id": "894:6718",
    "name": "Admin / Story Review — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "08 — Stories, Content & Moderation",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "story-review",
    "pendingReason": null
  },
  {
    "id": "894:6853",
    "name": "Admin / Story Review — Request Revision",
    "w": 1440,
    "h": 1100,
    "section": "08 — Stories, Content & Moderation",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "story-review-request-revision",
    "pendingReason": null
  },
  {
    "id": "894:7005",
    "name": "Admin / Story Review — Approve Confirmation",
    "w": 1440,
    "h": 1100,
    "section": "08 — Stories, Content & Moderation",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "story-review-approve-confirmation",
    "pendingReason": null
  },
  {
    "id": "894:7156",
    "name": "Admin / Content Operations — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "08 — Stories, Content & Moderation",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "content-operations",
    "pendingReason": null
  },
  {
    "id": "899:242",
    "name": "Admin / Export Partners — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "09 - Export Partners & International Operations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "export-partners",
    "pendingReason": null
  },
  {
    "id": "899:446",
    "name": "Admin / Export Partners — Loading",
    "w": 1440,
    "h": 1100,
    "section": "09 - Export Partners & International Operations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "export-partners-loading",
    "pendingReason": null
  },
  {
    "id": "899:580",
    "name": "Admin / Export Partners — Empty",
    "w": 1440,
    "h": 1100,
    "section": "09 - Export Partners & International Operations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "export-partners-empty",
    "pendingReason": null
  },
  {
    "id": "899:680",
    "name": "Admin / Export Partners — Error",
    "w": 1440,
    "h": 1100,
    "section": "09 - Export Partners & International Operations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "export-partners-error",
    "pendingReason": null
  },
  {
    "id": "899:796",
    "name": "Admin / Export Partner Detail — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "09 - Export Partners & International Operations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "export-partner-detail",
    "pendingReason": null
  },
  {
    "id": "899:1017",
    "name": "Admin / Export Markets — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "09 - Export Partners & International Operations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "export-markets",
    "pendingReason": null
  },
  {
    "id": "899:1197",
    "name": "Admin / Export Market Detail — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "09 - Export Partners & International Operations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "export-market-detail",
    "pendingReason": null
  },
  {
    "id": "899:1374",
    "name": "Admin / Export Market Catalog — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "09 - Export Partners & International Operations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "export-market-catalog",
    "pendingReason": null
  },
  {
    "id": "899:1594",
    "name": "Admin / Partner Commercial Terms — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "09 - Export Partners & International Operations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "partner-commercial-terms",
    "pendingReason": null
  },
  {
    "id": "899:1970",
    "name": "Admin / Export Orders — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "09 - Export Partners & International Operations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "export-orders",
    "pendingReason": null
  },
  {
    "id": "899:2152",
    "name": "Admin / Export Order Detail - Desktop",
    "w": 1440,
    "h": 1100,
    "section": "09 - Export Partners & International Operations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "export-order-detail",
    "pendingReason": null
  },
  {
    "id": "899:2334",
    "name": "Admin / Export Operations — Needs Action — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "09 - Export Partners & International Operations",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "export-operations-needs-action",
    "pendingReason": null
  },
  {
    "id": "903:247",
    "name": "Admin / Reports — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "10 — Reports, Settings & Permissions",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "reports",
    "pendingReason": null
  },
  {
    "id": "903:518",
    "name": "Admin / Report Detail — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "10 — Reports, Settings & Permissions",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "report-detail",
    "pendingReason": null
  },
  {
    "id": "903:739",
    "name": "Admin / Settings — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "10 — Reports, Settings & Permissions",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "settings",
    "pendingReason": null
  },
  {
    "id": "903:914",
    "name": "Admin / Notification Settings — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "10 — Reports, Settings & Permissions",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "notification-settings",
    "pendingReason": null
  },
  {
    "id": "903:1571",
    "name": "Admin / Staff & Access — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "10 — Reports, Settings & Permissions",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "staff-and-access",
    "pendingReason": null
  },
  {
    "id": "903:1727",
    "name": "Admin / Staff Access Detail — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "10 — Reports, Settings & Permissions",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "staff-access-detail",
    "pendingReason": null
  },
  {
    "id": "903:1861",
    "name": "Admin / Roles & Permissions — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "10 — Reports, Settings & Permissions",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "roles-and-permissions",
    "pendingReason": null
  },
  {
    "id": "903:1991",
    "name": "Admin / Role Detail — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "10 — Reports, Settings & Permissions",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "role-detail",
    "pendingReason": null
  },
  {
    "id": "903:2161",
    "name": "Admin / Role Editor — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "10 — Reports, Settings & Permissions",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "role-editor",
    "pendingReason": null
  },
  {
    "id": "903:2610",
    "name": "Admin / Operational Audit — Desktop",
    "w": 1440,
    "h": 1100,
    "section": "10 — Reports, Settings & Permissions",
    "contextReceived": true,
    "assetsMissing": [],
    "implemented": true,
    "slug": "operational-audit",
    "pendingReason": null
  }
] as const;
export const adminLoaders = {
  "dashboard": () => import("./screens/dashboard"),
  "dashboard-no-pending-actions": () => import("./screens/dashboard-no-pending-actions"),
  "dashboard-loading": () => import("./screens/dashboard-loading"),
  "dashboard-error": () => import("./screens/dashboard-error"),
  "artists": () => import("./screens/artists"),
  "artists-loading": () => import("./screens/artists-loading"),
  "artists-empty": () => import("./screens/artists-empty"),
  "artists-error": () => import("./screens/artists-error"),
  "artist-detail": () => import("./screens/artist-detail"),
  "professional-credentials": () => import("./screens/professional-credentials"),
  "credential-review": () => import("./screens/credential-review"),
  "credential-request-replacement": () => import("./screens/credential-request-replacement"),
  "credential-approve-confirmation": () => import("./screens/credential-approve-confirmation"),
  "products": () => import("./screens/products"),
  "products-loading": () => import("./screens/products-loading"),
  "products-empty": () => import("./screens/products-empty"),
  "products-error": () => import("./screens/products-error"),
  "product-detail": () => import("./screens/product-detail"),
  "product-review-queue": () => import("./screens/product-review-queue"),
  "product-review-new-product": () => import("./screens/product-review-new-product"),
  "product-review-request-revision": () => import("./screens/product-review-request-revision"),
  "product-review-approve-confirmation": () => import("./screens/product-review-approve-confirmation"),
  "product-review-published-changes": () => import("./screens/product-review-published-changes"),
  "product-review-changes-request-revision": () => import("./screens/product-review-changes-request-revision"),
  "product-review-changes-approve-confirmation": () => import("./screens/product-review-changes-approve-confirmation"),
  "orders": () => import("./screens/orders"),
  "orders-loading": () => import("./screens/orders-loading"),
  "orders-empty": () => import("./screens/orders-empty"),
  "orders-error": () => import("./screens/orders-error"),
  "order-detail": () => import("./screens/order-detail"),
  "orders-needs-action": () => import("./screens/orders-needs-action"),
  "order-issues": () => import("./screens/order-issues"),
  "order-issue-detail": () => import("./screens/order-issue-detail"),
  "shipping-operations": () => import("./screens/shipping-operations"),
  "shipment-detail": () => import("./screens/shipment-detail"),
  "growth-overview": () => import("./screens/growth-overview"),
  "growth-reviews": () => import("./screens/growth-reviews"),
  "growth-artist-detail": () => import("./screens/growth-artist-detail"),
  "services": () => import("./screens/services"),
  "service-requests": () => import("./screens/service-requests"),
  "services-needs-assignment": () => import("./screens/services-needs-assignment"),
  "service-request-detail": () => import("./screens/service-request-detail"),
  "service-assignment": () => import("./screens/service-assignment"),
  "service-partners": () => import("./screens/service-partners"),
  "service-partner-detail": () => import("./screens/service-partner-detail"),
  "opportunities": () => import("./screens/opportunities"),
  "opportunities-loading": () => import("./screens/opportunities-loading"),
  "opportunities-empty": () => import("./screens/opportunities-empty"),
  "opportunities-error": () => import("./screens/opportunities-error"),
  "opportunity-detail": () => import("./screens/opportunity-detail"),
  "opportunity-applications": () => import("./screens/opportunity-applications"),
  "opportunity-application-detail": () => import("./screens/opportunity-application-detail"),
  "capacity-matching": () => import("./screens/capacity-matching"),
  "order-allocation": () => import("./screens/order-allocation"),
  "corporate-request-detail": () => import("./screens/corporate-request-detail"),
  "corporate-requests": () => import("./screens/corporate-requests"),
  "corporate-buyer-detail": () => import("./screens/corporate-buyer-detail"),
  "corporate-buyers": () => import("./screens/corporate-buyers"),
  "supporting-organizations": () => import("./screens/supporting-organizations"),
  "supporting-organization-detail": () => import("./screens/supporting-organization-detail"),
  "organization-artist-referrals": () => import("./screens/organization-artist-referrals"),
  "finance-overview": () => import("./screens/finance-overview"),
  "settlement-requests": () => import("./screens/settlement-requests"),
  "settlement-detail": () => import("./screens/settlement-detail"),
  "settlement-review": () => import("./screens/settlement-review"),
  "settlement-confirmation": () => import("./screens/settlement-confirmation"),
  "transactions": () => import("./screens/transactions"),
  "transaction-detail-sale": () => import("./screens/transaction-detail-sale"),
  "transaction-detail-settlement": () => import("./screens/transaction-detail-settlement"),
  "transaction-detail-refund": () => import("./screens/transaction-detail-refund"),
  "memberships": () => import("./screens/memberships"),
  "membership-detail": () => import("./screens/membership-detail"),
  "membership-upgrade-detail": () => import("./screens/membership-upgrade-detail"),
  "stories": () => import("./screens/stories"),
  "stories-loading": () => import("./screens/stories-loading"),
  "stories-empty": () => import("./screens/stories-empty"),
  "stories-error": () => import("./screens/stories-error"),
  "story-detail": () => import("./screens/story-detail"),
  "story-review-queue": () => import("./screens/story-review-queue"),
  "story-review": () => import("./screens/story-review"),
  "story-review-request-revision": () => import("./screens/story-review-request-revision"),
  "story-review-approve-confirmation": () => import("./screens/story-review-approve-confirmation"),
  "content-operations": () => import("./screens/content-operations"),
  "export-partners": () => import("./screens/export-partners"),
  "export-partners-loading": () => import("./screens/export-partners-loading"),
  "export-partners-empty": () => import("./screens/export-partners-empty"),
  "export-partners-error": () => import("./screens/export-partners-error"),
  "export-partner-detail": () => import("./screens/export-partner-detail"),
  "export-markets": () => import("./screens/export-markets"),
  "export-market-detail": () => import("./screens/export-market-detail"),
  "export-market-catalog": () => import("./screens/export-market-catalog"),
  "partner-commercial-terms": () => import("./screens/partner-commercial-terms"),
  "export-orders": () => import("./screens/export-orders"),
  "export-order-detail": () => import("./screens/export-order-detail"),
  "export-operations-needs-action": () => import("./screens/export-operations-needs-action"),
  "reports": () => import("./screens/reports"),
  "report-detail": () => import("./screens/report-detail"),
  "settings": () => import("./screens/settings"),
  "notification-settings": () => import("./screens/notification-settings"),
  "staff-and-access": () => import("./screens/staff-and-access"),
  "staff-access-detail": () => import("./screens/staff-access-detail"),
  "roles-and-permissions": () => import("./screens/roles-and-permissions"),
  "role-detail": () => import("./screens/role-detail"),
  "role-editor": () => import("./screens/role-editor"),
  "operational-audit": () => import("./screens/operational-audit")
};
export type AdminScreenSlug = keyof typeof adminLoaders;
